#!/bin/bash

i=$1

printf -v hex '%x' "$i"
printf -v letter "\\x$hex"
varname=xxxx
VARNAME=XXXX
cat <<EOF
#define INIT_${VARNAME}() \\
static const uint8_t ${varname}_pixels[] PROGMEM = {\\
	0,0,0,0,0,0,\\
	0,0,0,0,0,0,\\
	0,0,0,0,0,0,\\
	0,0,0,0,0,0,\\
	0,0,0,0,0,0,\\
	0,0,0,0,0,0,\\
	0,0,0,0,0,0,\\
	0,0,0,0,0,0\\
};

#define LOAD_${VARNAME}() \\
charTable.pixels['${letter}'] = ${varname}_pixels;\\
charTable.width['${letter}'] = 6;

EOF
